export function language(locale) {
  return /^(?:nb|nn|no)(?:-|$)/i.test(String(locale || "nb")) ? "nb" : "en";
}

const copy = {
  nb: {
    meta: "Utforsk produkter og kolleksjoner hos",
    skip: "Hopp til innhold",
    shop: "Butikk",
    collections: "Kolleksjoner",
    about: "Om oss",
    contact: "Kontakt",
    cart: "Handlekurv",
    allProducts: "Alle produkter",
    yourCart: "Din handlekurv",
    help: "Hjelp",
    shipping: "Frakt og levering",
    faq: "Ofte stilte spørsmål",
    returns: "Retur",
    ourStory: "Historien vår",
    privacy: "Personvern",
    terms: "Kjøpsvilkår",
    poweredBy: "Drevet av",
    viewProduct: "Se produkt",
    from: "Fra ",
    discoverProducts: "Se produktene",
    collectionEyebrow: "01 / Utforsk",
    exploreCollections: "Utforsk kolleksjonene",
    productsEyebrow: "02 / Oppdag",
    ourProducts: "Våre produkter",
    emptyProducts: "Ingen produkter er publisert ennå. Kom gjerne tilbake senere.",
    meetStore: "Bli kjent med butikken",
    storyHeading: "Mer enn en handleliste.",
    knowUs: "Les mer om oss",
    curatedSelection: "Utvalgte produkter",
    latestArrivals: "Oppdag det nyeste i butikken",
    clearCheckout: "Oversiktlig betaling",
    reviewOrder: "Se over ordren før du betaler",
    hereHelp: "Vi hjelper deg",
    getInTouch: "Ta kontakt",
    collection: "Kolleksjon",
    noCollectionProducts: "Denne kolleksjonen har ingen publiserte produkter ennå.",
    noCollections: "Ingen kolleksjoner er publisert ennå.",
    backAllProducts: "← Alle produkter",
    backStore: "← Tilbake til butikken",
    standard: "Standard",
    options: "Varianter",
    quantity: "Antall",
    addToCart: "Legg i handlekurv",
    continueShopping: "← Fortsett å handle",
    loadingCart: "Laster handlekurven…",
    checkout: "Gå til kassen",
    cartNote: "ReAI kontrollerer priser, lagerstatus, frakt og betaling på den sikre betalingssiden.",
    orderComplete: "Bestilling fullført",
    thankYou: "Takk for handelen",
    orderCompleteHeading: "Bestillingen din er fullført.",
    orderCompleteText: "Betalingen er gjennomført i ReAIs kasse. Se etter ordrebekreftelsen din.",
    continueToStore: "Fortsett å handle",
    business: "Registrert virksomhet",
    organizationNumber: "Organisasjonsnummer",
    address: "Forretningsadresse",
    fallbackContact: "kontaktadressen i ordrebekreftelsen",
    exploreCollection: "Utforsk utvalget",
    comingSoon: "Kommer snart",
    setupHeading: "Noe fint er på vei.",
    setupText: "Denne nettbutikken er under oppsett.",
    notFound: "Fant ikke siden",
    notFoundHeading: "Vi fant ikke denne siden.",
    backToStore: "Tilbake til butikken",
    temporarilyUnavailable: "Midlertidig utilgjengelig",
    tryAgain: "Prøv igjen senere",
    unavailableHeading: "Butikken er midlertidig utilgjengelig.",
    unavailableText: "Vi kunne ikke laste inn produktene akkurat nå.",
  },
  en: {
    meta: "Explore products and collections at",
    skip: "Skip to content",
    shop: "Shop",
    collections: "Collections",
    about: "About",
    contact: "Contact",
    cart: "Cart",
    allProducts: "All products",
    yourCart: "Your cart",
    help: "Help",
    shipping: "Shipping & delivery",
    faq: "FAQs",
    returns: "Returns",
    ourStory: "Our story",
    privacy: "Privacy",
    terms: "Terms of sale",
    poweredBy: "Powered by",
    viewProduct: "View product",
    from: "From ",
    discoverProducts: "Explore products",
    collectionEyebrow: "01 / Browse",
    exploreCollections: "Explore collections",
    productsEyebrow: "02 / Discover",
    ourProducts: "Our products",
    emptyProducts: "No products have been published yet. Check back soon.",
    meetStore: "Meet the store",
    storyHeading: "More than a shopping list.",
    knowUs: "Get to know us",
    curatedSelection: "Curated selection",
    latestArrivals: "Discover the latest arrivals",
    clearCheckout: "Clear checkout",
    reviewOrder: "Review your order before payment",
    hereHelp: "Here to help",
    getInTouch: "Get in touch",
    collection: "Collection",
    noCollectionProducts: "This collection has no published products yet.",
    noCollections: "No collections have been published yet.",
    backAllProducts: "← All products",
    backStore: "← Back to the store",
    standard: "Standard",
    options: "Options",
    quantity: "Quantity",
    addToCart: "Add to cart",
    continueShopping: "← Continue shopping",
    loadingCart: "Loading cart…",
    checkout: "Continue to checkout",
    cartNote: "ReAI confirms prices, availability, shipping and payment on the secure checkout page.",
    orderComplete: "Order complete",
    thankYou: "Thank you",
    orderCompleteHeading: "Your order is complete.",
    orderCompleteText: "Your payment was completed in ReAI checkout. Look for your order confirmation.",
    continueToStore: "Continue shopping",
    business: "Registered business",
    organizationNumber: "Registration number",
    address: "Business address",
    fallbackContact: "the contact address in your order confirmation",
    exploreCollection: "Explore the collection",
    comingSoon: "Coming soon",
    setupHeading: "Something good is on its way.",
    setupText: "This storefront is being set up.",
    notFound: "Not found",
    notFoundHeading: "We couldn't find that page.",
    backToStore: "Back to the store",
    temporarilyUnavailable: "Temporarily unavailable",
    tryAgain: "Please try again",
    unavailableHeading: "The store is temporarily unavailable.",
    unavailableText: "We couldn't load the catalog right now.",
  },
};

export function ui(locale) {
  return copy[language(locale)];
}
